name: Workflow commands

on:
  push:
    branches:
      - main

jobs:
  workflow-commands:
   runs-on: ubuntu-latest
   steps:
     - name: group loggins
       run: |
         echo "::group::My Group"
         echo "msg 1"
         echo "msg 2"
         echo "::endgroup::"