name: conditionals

on:
  push:
    branches:
      - main

jobs:
  expressions:
    runs-on: ubuntu-latest
    steps:
      - name: contains
        if: contains(github.repository, Darker)
        run: echo This repo contains Darker
      - name: startsWith
        if: startsWith(test,te)
        run: echo this words starts with te